###Pandas1


In [4]:
import pandas

In [3]:
!pip install pandas

  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
    --------------------------------------- 0.3/11.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.6 MB 4.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/11.6 MB 3.2 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/11.6 MB 3.8 MB/s eta 0:00:03
   ---------- ----------------------------- 3.1/11.6 MB 3.5 MB/s eta 0:00:03
   ------------- -------------------------- 3.9/11.6 MB 3.4 MB/s eta 0:00:03
   --------------- ------------------------ 4.5/11.6 MB 3.3 MB/s eta 0:00:03
   ------------------ --------------------- 5.2/11.6 MB 3.3 MB/s eta 0:00:02
   ------------------- -------------------- 5.8/11.6 MB 3.2 MB/s eta 0:00:02
   --------------------- ------------------ 6.3/11.6 MB 3.2 MB/s eta 0:00:02
   ------------------------ --------------- 7.1/11.6 MB 3.2 MB/s eta 0:00:02
   ----------------------

In [3]:
import pandas as pd
# print(pd.__version__)

ModuleNotFoundError: No module named 'pandas'

In [2]:
open cmd

##type python -m pip install pandas

#restart your Visual Studio Code

SyntaxError: invalid syntax (226574278.py, line 1)

In [5]:
import numpy as np


In [7]:
# From a Python list
arr1 = np.array([1, 2, 3])  # 1D array
print(arr1)
# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print (arr2)
# Array of zeros
zeros = np.zeros((2, 3))
print(zeros)
# Array of ones
ones = np.ones((3, 2))
print(ones)
# Array with a range of values
range_arr = np.arange(0, 10, 2)
print(range_arr)
# Random values
random_arr = np.random.rand(2, 3)
print(random_arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[[0.74259955 0.38173892 0.3720761 ]
 [0.9951436  0.51845746 0.07342794]]


In [8]:
arr = np.array([1, 2, 3])
print(arr.dtype)  # int64 or int32 depending on system

# You can set the data type
arr_float = np.array([1, 2, 3], dtype='float32')
print(arr_float.dtype)  # float32


int64
float32


In [5]:
#Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

import numpy as np
array1=np.array([1,2,3,4,5])
print(type(array1))
print(array1)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [8]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

array3=np.array([[2,3,4], [5,6,7],[8,9,10]])
print(array3)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [14]:
# Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
zeros=np.zeros(10)
print(zeros)
zeros[5]=11
print(zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [16]:
# Write a NumPy program to create an array with values ranging from 12 to 38.
range_arr=np.arange(12,38)
print(range_arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [18]:
#Write a NumPy program to convert an array to a floating type.
float_array=np.array([4,5,6,7],dtype='float32')
print(float_array)
print(type(float_array))


[4. 5. 6. 7.]
<class 'numpy.ndarray'>


In [19]:
#Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.
centigrade = np.array([0, 20, 37, 100])

# Convert to Fahrenheit
fahrenheit = centigrade * 9/5 + 32

# Print the result
print("Centigrade:", centigrade)
print("Fahrenheit:", fahrenheit)


Centigrade: [  0  20  37 100]
Fahrenheit: [ 32.   68.   98.6 212. ]


In [20]:
# Write a NumPy program to append values to the end of an array.
original_arr=np.array([10,20,30])
append_value=[40,50,60,70,80,90]
new_arr=np.append(original_arr, append_value)
print(new_arr)


[10 20 30 40 50 60 70 80 90]


In [21]:
#Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.

random_array = np.random.rand(10)  

mean = np.mean(random_array)
median = np.median(random_array)
std_dev = np.std(random_array)

print("Random array:", random_array)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Random array: [0.97610146 0.22634222 0.07511747 0.64229765 0.45050529 0.61371616
 0.99106747 0.56817413 0.32052695 0.29229082]
Mean: 0.5156139614938212
Median: 0.5093397087117142
Standard Deviation: 0.2892104352709543


In [23]:
#Create a 10x10 array with random values and find the minimum and maximum values.
random_array = np.random.rand(10,10)  
Min_value=np.min(random_array)
MAx_value=np.max(random_array)
print('the minimum value in random array is :', Min_value)
print('The max value in random_array is :',MAx_value)

the minimum value in random array is : 0.005668732775439778
The max value in random_array is : 0.9998421885410359


In [24]:
#Create a 3x3x3 array with random values.
random_array = np.random.rand(3,3,3)  
print('the 3X3X3 random arraey is :', random_array)



the 3X3X3 random arraey is : [[[0.90845264 0.02397827 0.67337116]
  [0.863812   0.96384848 0.86453013]
  [0.64892469 0.38868123 0.06816745]]

 [[0.56170128 0.54473169 0.67029635]
  [0.43626038 0.09239184 0.82646751]
  [0.01526601 0.18645956 0.88706143]]

 [[0.87822857 0.73676589 0.32299308]
  [0.00644817 0.73089559 0.69478849]
  [0.50061151 0.00436485 0.15693227]]]
